[package]
name = "plinter_api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
typed-arena = "2.0.1"
smallvec = "1.6.1"
