[package]
name = "test_lint"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plinter_api = { path = "../plinter_api" }
# driver = { path = "../driver" }

[lib]
crate-type = ["cdylib"]
