[alias]
pclippy = """\
  clippy --package pluggy_api -- \
    -W rust_2018_idioms \
    -W semicolon_in_expressions_from_macros \
    -W unused_import_braces \
    -W unused_qualifications \
    -W clippy::branches_sharing_code \
    -W clippy::cloned_instead_of_copied \
    -W clippy::dbg_macro \
    -W clippy::disallowed_type \
    -W clippy::empty_line_after_outer_attr \
    -W clippy::exhaustive_enums \
    -W clippy::inefficient_to_string \
    -W clippy::macro_use_imports \
    -W clippy::map_flatten \
    -W clippy::missing_enforced_import_renames \
    -W clippy::mut_mut \
    -W clippy::needless_borrow \
    -A clippy::new_without_default \
    -W clippy::nonstandard_macro_braces \
    -W clippy::str_to_string \
    -W clippy::todo \
    -W clippy::unreadable_literal \
    -W clippy::unseparated_literal_suffix \
    -W clippy::useless_let_if_seq \
    -W clippy::wildcard_imports \
"""
#   -W clippy::exhaustive_structs \
